// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AdminCompareResp struct {
	HasDiff                 bool                      `json:"has_diff"`
	DiffFields              []string                  `json:"diff_fields"`
	LocalOverrideDiffFields []string                  `json:"local_override_diff_fields"`
	DiffDetails             []AdminCompareFieldDetail `json:"diff_details"`
	Message                 string                    `json:"message"`
}

type AdminCompareFieldDetail struct {
	Field    string `json:"field"`
	DiffType string `json:"diff_type"`
	Local    string `json:"local"`
	Remote   string `json:"remote"`
}

type AdminCreateMovieReq struct {
	Title            string   `json:"title"`
	OriginalTitle    string   `json:"original_title,optional"`
	Overview         string   `json:"overview,optional"`
	Tagline          string   `json:"tagline,optional"`
	ReleaseDate      string   `json:"release_date,optional"`
	Status           string   `json:"status,optional"`
	Runtime          *int     `json:"runtime,optional"`
	OriginalLanguage string   `json:"original_language,optional"`
	Homepage         string   `json:"homepage,optional"`
	PosterPath       string   `json:"poster_path,optional"`
	BackdropPath     string   `json:"backdrop_path,optional"`
	VoteAverage      *float64 `json:"vote_average,optional"`
	Popularity       *float64 `json:"popularity,optional"`
	GenreNames       []string `json:"genre_names,optional"`
}

type AdminCreateResp struct {
	TmdbId     int    `json:"tmdb_id"`
	SyncTmdbId int    `json:"sync_tmdb_id"`
	IsLocal    bool   `json:"is_local"`
	Message    string `json:"message"`
}

type AdminProxyReq struct {
	ProxyURL string `json:"proxy_url,optional"`
}

type AdminProxyResp struct {
	ProxyURL string `json:"proxy_url"`
	Enabled  bool   `json:"enabled"`
}

type AdminAutoSyncReq struct {
	Enabled          *bool  `json:"enabled,optional"`
	CronExpr         string `json:"cron_expr,optional"`
	Mode             string `json:"mode,optional"`
	BatchSize        *int   `json:"batch_size,optional"`
	StartDelaySecond *int   `json:"start_delay_second,optional"`
}

type AdminAutoSyncResp struct {
	Enabled          bool   `json:"enabled"`
	CronExpr         string `json:"cron_expr"`
	Mode             string `json:"mode"`
	BatchSize        int    `json:"batch_size"`
	StartDelaySecond int    `json:"start_delay_second"`
	Running          bool   `json:"running"`
}

type AdminAutoSyncRunResp struct {
	Started bool   `json:"started"`
	Running bool   `json:"running"`
	Message string `json:"message"`
}

type AdminAutoSyncLogClearResp struct {
	Message string `json:"message"`
}

type AdminAutoSyncLogListReq struct {
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"page_size,optional,default=20"`
	Status   string `form:"status,optional"`
}

type AdminAutoSyncLogItem struct {
	Id          int64  `json:"id"`
	TriggeredAt string `json:"triggered_at"`
	CronExpr    string `json:"cron_expr"`
	Mode        string `json:"mode"`
	BatchSize   int    `json:"batch_size"`
	Status      string `json:"status"`
	Checked     int    `json:"checked"`
	Synced      int    `json:"synced"`
	Failed      int    `json:"failed"`
	DurationMs  int64  `json:"duration_ms"`
	Message     string `json:"message"`
	StartedAt   string `json:"started_at"`
	FinishedAt  string `json:"finished_at"`
	CreatedAt   string `json:"created_at"`
}

type AdminAutoSyncLogDetailReq struct {
	Id             int `path:"id"`
	SyncedPage     int `form:"synced_page,optional,default=1"`
	SyncedPageSize int `form:"synced_page_size,optional,default=10"`
	FailedPage     int `form:"failed_page,optional,default=1"`
	FailedPageSize int `form:"failed_page_size,optional,default=10"`
}

type AdminAutoSyncLogDetailEntry struct {
	MediaType         string                        `json:"media_type"`
	TmdbId            int                           `json:"tmdb_id"`
	Name              string                        `json:"name"`
	Message           string                        `json:"message"`
	RemoteDiffFields  []string                      `json:"remote_diff_fields"`
	FieldChanges      []AdminAutoSyncLogFieldChange `json:"field_changes"`
	ChangedFields     []string                      `json:"changed_fields"`
	OverwrittenFields []string                      `json:"overwritten_fields"`
	KeptLocalFields   []string                      `json:"kept_local_fields"`
}

type AdminAutoSyncLogFieldChange struct {
	Field    string `json:"field"`
	DiffType string `json:"diff_type"`
	Before   string `json:"before"`
	After    string `json:"after"`
}

type AdminAutoSyncLogDetailResp struct {
	Id             int64                         `json:"id"`
	TriggeredAt    string                        `json:"triggered_at"`
	CronExpr       string                        `json:"cron_expr"`
	Mode           string                        `json:"mode"`
	BatchSize      int                           `json:"batch_size"`
	Status         string                        `json:"status"`
	Checked        int                           `json:"checked"`
	Synced         int                           `json:"synced"`
	Failed         int                           `json:"failed"`
	DurationMs     int64                         `json:"duration_ms"`
	Message        string                        `json:"message"`
	StartedAt      string                        `json:"started_at"`
	FinishedAt     string                        `json:"finished_at"`
	CreatedAt      string                        `json:"created_at"`
	SyncedPage     int                           `json:"synced_page"`
	SyncedPageSize int                           `json:"synced_page_size"`
	SyncedList     []AdminAutoSyncLogDetailEntry `json:"synced_list"`
	FailedPage     int                           `json:"failed_page"`
	FailedPageSize int                           `json:"failed_page_size"`
	FailedList     []AdminAutoSyncLogDetailEntry `json:"failed_list"`
}

type AdminAutoSyncLogListResp struct {
	Total    int64                  `json:"total"`
	Page     int                    `json:"page"`
	PageSize int                    `json:"page_size"`
	Results  []AdminAutoSyncLogItem `json:"results"`
}

type AdminSyncReq struct {
	Id              int      `path:"id"`
	Mode            string   `json:"mode,optional"`
	OverwriteFields []string `json:"overwrite_fields,optional"`
}

type AdminSyncResp struct {
	Mode            string   `json:"mode"`
	ChangedFields   []string `json:"changed_fields"`
	Overwritten     []string `json:"overwritten_fields"`
	KeptLocalFields []string `json:"kept_local_fields"`
	IsModified      bool     `json:"is_modified"`
	Message         string   `json:"message"`
}

type AdminUpdateReq struct {
	Id               int      `path:"id"`
	TmdbId           *int     `json:"tmdb_id,optional"`
	Title            *string  `json:"title,optional"`
	OriginalTitle    *string  `json:"original_title,optional"`
	Overview         *string  `json:"overview,optional"`
	Tagline          *string  `json:"tagline,optional"`
	ReleaseDate      *string  `json:"release_date,optional"`
	Status           *string  `json:"status,optional"`
	Runtime          *int     `json:"runtime,optional"`
	OriginalLanguage *string  `json:"original_language,optional"`
	Homepage         *string  `json:"homepage,optional"`
	PosterPath       *string  `json:"poster_path,optional"`
	BackdropPath     *string  `json:"backdrop_path,optional"`
	VoteAverage      *float64 `json:"vote_average,optional"`
	Popularity       *float64 `json:"popularity,optional"`
	GenreNames       []string `json:"genre_names,optional"`
	Name             *string  `json:"name,optional"`
	OriginalName     *string  `json:"original_name,optional"`
	FirstAirDate     *string  `json:"first_air_date,optional"`
	NumberOfSeasons  *int     `json:"number_of_seasons,optional"`
	NumberOfEpisodes *int     `json:"number_of_episodes,optional"`
	Type             *string  `json:"type,optional"`
}

type AdminUploadResp struct {
	Path string `json:"path"`
}

type AdminCreateTvReq struct {
	Name             string   `json:"name"`
	OriginalName     string   `json:"original_name,optional"`
	Overview         string   `json:"overview,optional"`
	Tagline          string   `json:"tagline,optional"`
	FirstAirDate     string   `json:"first_air_date,optional"`
	Status           string   `json:"status,optional"`
	NumberOfSeasons  *int     `json:"number_of_seasons,optional"`
	NumberOfEpisodes *int     `json:"number_of_episodes,optional"`
	OriginalLanguage string   `json:"original_language,optional"`
	Homepage         string   `json:"homepage,optional"`
	PosterPath       string   `json:"poster_path,optional"`
	BackdropPath     string   `json:"backdrop_path,optional"`
	VoteAverage      *float64 `json:"vote_average,optional"`
	Popularity       *float64 `json:"popularity,optional"`
	Type             string   `json:"type,optional"`
	GenreNames       []string `json:"genre_names,optional"`
}

type DetailReq struct {
	Id               int    `path:"id"`
	Language         string `form:"language,optional"`
	AppendToResponse string `form:"append_to_response,optional"`
}

type DiscoverReq struct {
	Language             string `form:"language,optional"`
	Page                 int    `form:"page,optional,default=1"`
	Region               string `form:"region,optional"`
	SortBy               string `form:"sort_by,optional"`
	WithGenres           string `form:"with_genres,optional"`
	PrimaryReleaseYear   int    `form:"primary_release_year,optional"`
	FirstAirDateYear     int    `form:"first_air_date_year,optional"`
	VoteAverageGte       string `form:"vote_average.gte,optional"`
	VoteAverageLte       string `form:"vote_average.lte,optional"`
	WithOriginalLanguage string `form:"with_original_language,optional"`
}

type FindByExternalIdReq struct {
	ExternalId     string `path:"external_id"`
	ExternalSource string `form:"external_source"`
	Language       string `form:"language,optional"`
}

type GenreListReq struct {
	Language string `form:"language,optional"`
}

type LibraryListReq struct {
	Page       int    `form:"page,optional,default=1"`
	PageSize   int    `form:"page_size,optional,default=20"`
	Keyword    string `form:"keyword,optional"`
	SearchMode string `form:"search_mode,optional,default=contains"`
}

type MovieListItem struct {
	TmdbId        int      `json:"tmdb_id"`
	Title         string   `json:"title"`
	OriginalTitle string   `json:"original_title"`
	PosterPath    string   `json:"poster_path"`
	VoteAverage   float64  `json:"vote_average"`
	ReleaseDate   string   `json:"release_date"`
	Popularity    float64  `json:"popularity"`
	IsModified    bool     `json:"is_modified"`
	GenreNames    []string `json:"genre_names"`
}

type MovieListResp struct {
	Total    int64           `json:"total"`
	Page     int             `json:"page"`
	PageSize int             `json:"page_size"`
	Results  []MovieListItem `json:"results"`
}

type PageReq struct {
	Language string `form:"language,optional"`
	Page     int    `form:"page,optional,default=1"`
	Region   string `form:"region,optional"`
}

type PathIdReq struct {
	Id int `path:"id"`
}

type SearchReq struct {
	Query    string `form:"query"`
	Language string `form:"language,optional"`
	Page     int    `form:"page,optional,default=1"`
	Region   string `form:"region,optional"`
}

type TrendingReq struct {
	MediaType  string `path:"media_type"`
	TimeWindow string `path:"time_window"`
	Language   string `form:"language,optional"`
	Page       int    `form:"page,optional,default=1"`
}

type TvEpisodeReq struct {
	SeriesId      int    `path:"series_id"`
	SeasonNumber  int    `path:"season_number"`
	EpisodeNumber int    `path:"episode_number"`
	Language      string `form:"language,optional"`
}

type TvSeasonReq struct {
	SeriesId     int    `path:"series_id"`
	SeasonNumber int    `path:"season_number"`
	Language     string `form:"language,optional"`
}

type TvSeriesListItem struct {
	TmdbId           int      `json:"tmdb_id"`
	Name             string   `json:"name"`
	OriginalName     string   `json:"original_name"`
	PosterPath       string   `json:"poster_path"`
	VoteAverage      float64  `json:"vote_average"`
	FirstAirDate     string   `json:"first_air_date"`
	NumberOfSeasons  int      `json:"number_of_seasons"`
	NumberOfEpisodes int      `json:"number_of_episodes"`
	Popularity       float64  `json:"popularity"`
	IsModified       bool     `json:"is_modified"`
	GenreNames       []string `json:"genre_names"`
}

type TvSeriesListResp struct {
	Total    int64              `json:"total"`
	Page     int                `json:"page"`
	PageSize int                `json:"page_size"`
	Results  []TvSeriesListItem `json:"results"`
}

type UploadFileReq struct {
	Filename string `path:"filename"`
}
