// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AdminCompareResp struct {
	HasDiff                 bool     `json:"has_diff"`
	DiffFields              []string `json:"diff_fields"`
	LocalOverrideDiffFields []string `json:"local_override_diff_fields"`
	Message                 string   `json:"message"`
}

type AdminProxyReq struct {
	ProxyURL string `json:"proxy_url,optional"`
}

type AdminProxyResp struct {
	ProxyURL string `json:"proxy_url"`
	Enabled  bool   `json:"enabled"`
}

type AdminSyncReq struct {
	Id              int      `path:"id"`
	Mode            string   `json:"mode,optional"`
	OverwriteFields []string `json:"overwrite_fields,optional"`
}

type AdminSyncResp struct {
	Mode            string   `json:"mode"`
	ChangedFields   []string `json:"changed_fields"`
	Overwritten     []string `json:"overwritten_fields"`
	KeptLocalFields []string `json:"kept_local_fields"`
	IsModified      bool     `json:"is_modified"`
	Message         string   `json:"message"`
}

type AdminUpdateReq struct {
	Id               int      `path:"id"`
	Title            *string  `json:"title,optional"`
	OriginalTitle    *string  `json:"original_title,optional"`
	Overview         *string  `json:"overview,optional"`
	Tagline          *string  `json:"tagline,optional"`
	ReleaseDate      *string  `json:"release_date,optional"`
	Status           *string  `json:"status,optional"`
	Runtime          *int     `json:"runtime,optional"`
	OriginalLanguage *string  `json:"original_language,optional"`
	Homepage         *string  `json:"homepage,optional"`
	PosterPath       *string  `json:"poster_path,optional"`
	BackdropPath     *string  `json:"backdrop_path,optional"`
	VoteAverage      *float64 `json:"vote_average,optional"`
	Popularity       *float64 `json:"popularity,optional"`
	GenreNames       []string `json:"genre_names,optional"`
	Name             *string  `json:"name,optional"`
	OriginalName     *string  `json:"original_name,optional"`
	FirstAirDate     *string  `json:"first_air_date,optional"`
	NumberOfSeasons  *int     `json:"number_of_seasons,optional"`
	NumberOfEpisodes *int     `json:"number_of_episodes,optional"`
	Type             *string  `json:"type,optional"`
}

type DetailReq struct {
	Id               int    `path:"id"`
	Language         string `form:"language,optional"`
	AppendToResponse string `form:"append_to_response,optional"`
}

type DiscoverReq struct {
	Language             string `form:"language,optional"`
	Page                 int    `form:"page,optional,default=1"`
	Region               string `form:"region,optional"`
	SortBy               string `form:"sort_by,optional"`
	WithGenres           string `form:"with_genres,optional"`
	PrimaryReleaseYear   int    `form:"primary_release_year,optional"`
	FirstAirDateYear     int    `form:"first_air_date_year,optional"`
	VoteAverageGte       string `form:"vote_average.gte,optional"`
	VoteAverageLte       string `form:"vote_average.lte,optional"`
	WithOriginalLanguage string `form:"with_original_language,optional"`
}

type FindByExternalIdReq struct {
	ExternalId     string `path:"external_id"`
	ExternalSource string `form:"external_source"`
	Language       string `form:"language,optional"`
}

type GenreListReq struct {
	Language string `form:"language,optional"`
}

type LibraryListReq struct {
	Page       int    `form:"page,optional,default=1"`
	PageSize   int    `form:"page_size,optional,default=20"`
	Keyword    string `form:"keyword,optional"`
	SearchMode string `form:"search_mode,optional,default=contains"`
}

type MovieListItem struct {
	TmdbId        int     `json:"tmdb_id"`
	Title         string  `json:"title"`
	OriginalTitle string  `json:"original_title"`
	PosterPath    string  `json:"poster_path"`
	VoteAverage   float64 `json:"vote_average"`
	ReleaseDate   string  `json:"release_date"`
	Popularity    float64 `json:"popularity"`
	IsModified    bool    `json:"is_modified"`
}

type MovieListResp struct {
	Total    int64           `json:"total"`
	Page     int             `json:"page"`
	PageSize int             `json:"page_size"`
	Results  []MovieListItem `json:"results"`
}

type PageReq struct {
	Language string `form:"language,optional"`
	Page     int    `form:"page,optional,default=1"`
	Region   string `form:"region,optional"`
}

type PathIdReq struct {
	Id int `path:"id"`
}

type SearchReq struct {
	Query    string `form:"query"`
	Language string `form:"language,optional"`
	Page     int    `form:"page,optional,default=1"`
	Region   string `form:"region,optional"`
}

type TrendingReq struct {
	MediaType  string `path:"media_type"`
	TimeWindow string `path:"time_window"`
	Language   string `form:"language,optional"`
	Page       int    `form:"page,optional,default=1"`
}

type TvEpisodeReq struct {
	SeriesId      int    `path:"series_id"`
	SeasonNumber  int    `path:"season_number"`
	EpisodeNumber int    `path:"episode_number"`
	Language      string `form:"language,optional"`
}

type TvSeasonReq struct {
	SeriesId     int    `path:"series_id"`
	SeasonNumber int    `path:"season_number"`
	Language     string `form:"language,optional"`
}

type TvSeriesListItem struct {
	TmdbId           int     `json:"tmdb_id"`
	Name             string  `json:"name"`
	OriginalName     string  `json:"original_name"`
	PosterPath       string  `json:"poster_path"`
	VoteAverage      float64 `json:"vote_average"`
	FirstAirDate     string  `json:"first_air_date"`
	NumberOfSeasons  int     `json:"number_of_seasons"`
	NumberOfEpisodes int     `json:"number_of_episodes"`
	Popularity       float64 `json:"popularity"`
	IsModified       bool    `json:"is_modified"`
}

type TvSeriesListResp struct {
	Total    int64              `json:"total"`
	Page     int                `json:"page"`
	PageSize int                `json:"page_size"`
	Results  []TvSeriesListItem `json:"results"`
}
