// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	admin "ms_tmdb/internal/handler/admin"
	discover "ms_tmdb/internal/handler/discover"
	misc "ms_tmdb/internal/handler/misc"
	movie "ms_tmdb/internal/handler/movie"
	movielist "ms_tmdb/internal/handler/movielist"
	person "ms_tmdb/internal/handler/person"
	personlist "ms_tmdb/internal/handler/personlist"
	search "ms_tmdb/internal/handler/search"
	trending "ms_tmdb/internal/handler/trending"
	tv "ms_tmdb/internal/handler/tv"
	tvlist "ms_tmdb/internal/handler/tvlist"
	tvseason "ms_tmdb/internal/handler/tvseason"
	"ms_tmdb/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/movie/:id",
				Handler: admin.UpdateMovieHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/movie/:id/local",
				Handler: admin.ClearMovieLocalHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/movies",
				Handler: admin.ListMoviesHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/person/:id",
				Handler: admin.UpdatePersonHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/stats",
				Handler: admin.GetStatsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sync/movie/:id",
				Handler: admin.SyncMovieHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sync/person/:id",
				Handler: admin.SyncPersonHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sync/tv/:id",
				Handler: admin.SyncTvSeriesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv-series",
				Handler: admin.ListTvSeriesHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/tv/:id",
				Handler: admin.UpdateTvSeriesHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/tv/:id/local",
				Handler: admin.ClearTvSeriesLocalHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/discover/movie",
				Handler: discover.DiscoverMovieHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/discover/tv",
				Handler: discover.DiscoverTvHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v3"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/configuration",
				Handler: misc.GetConfigurationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/find/:external_id",
				Handler: misc.FindByExternalIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/genre/movie/list",
				Handler: misc.GetGenreMovieListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/genre/tv/list",
				Handler: misc.GetGenreTvListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v3"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/movie/:id",
				Handler: movie.GetMovieDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/movie/:id/alternative_titles",
				Handler: movie.GetMovieAlternativeTitlesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/movie/:id/credits",
				Handler: movie.GetMovieCreditsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/movie/:id/external_ids",
				Handler: movie.GetMovieExternalIdsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/movie/:id/images",
				Handler: movie.GetMovieImagesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/movie/:id/keywords",
				Handler: movie.GetMovieKeywordsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/movie/:id/recommendations",
				Handler: movie.GetMovieRecommendationsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/movie/:id/release_dates",
				Handler: movie.GetMovieReleaseDatesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/movie/:id/similar",
				Handler: movie.GetMovieSimilarHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/movie/:id/translations",
				Handler: movie.GetMovieTranslationsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/movie/:id/videos",
				Handler: movie.GetMovieVideosHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/movie/:id/watch/providers",
				Handler: movie.GetMovieWatchProvidersHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v3"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/movie/now_playing",
				Handler: movielist.GetNowPlayingMoviesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/movie/popular",
				Handler: movielist.GetPopularMoviesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/movie/top_rated",
				Handler: movielist.GetTopRatedMoviesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/movie/upcoming",
				Handler: movielist.GetUpcomingMoviesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v3"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/person/:id",
				Handler: person.GetPersonDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/person/:id/combined_credits",
				Handler: person.GetPersonCombinedCreditsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/person/:id/external_ids",
				Handler: person.GetPersonExternalIdsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/person/:id/images",
				Handler: person.GetPersonImagesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/person/:id/movie_credits",
				Handler: person.GetPersonMovieCreditsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/person/:id/tv_credits",
				Handler: person.GetPersonTvCreditsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v3"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/person/popular",
				Handler: personlist.GetPopularPeopleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v3"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/search/collection",
				Handler: search.SearchCollectionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/company",
				Handler: search.SearchCompanyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/keyword",
				Handler: search.SearchKeywordHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/movie",
				Handler: search.SearchMovieHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/multi",
				Handler: search.SearchMultiHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/person",
				Handler: search.SearchPersonHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/tv",
				Handler: search.SearchTvHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v3"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/trending/:media_type/:time_window",
				Handler: trending.GetTrendingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v3"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/tv/:id",
				Handler: tv.GetTvSeriesDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/:id/aggregate_credits",
				Handler: tv.GetTvSeriesAggregateCreditsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/:id/content_ratings",
				Handler: tv.GetTvSeriesContentRatingsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/:id/credits",
				Handler: tv.GetTvSeriesCreditsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/:id/external_ids",
				Handler: tv.GetTvSeriesExternalIdsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/:id/images",
				Handler: tv.GetTvSeriesImagesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/:id/keywords",
				Handler: tv.GetTvSeriesKeywordsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/:id/recommendations",
				Handler: tv.GetTvSeriesRecommendationsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/:id/similar",
				Handler: tv.GetTvSeriesSimilarHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/:id/translations",
				Handler: tv.GetTvSeriesTranslationsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/:id/videos",
				Handler: tv.GetTvSeriesVideosHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/:id/watch/providers",
				Handler: tv.GetTvSeriesWatchProvidersHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v3"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/tv/airing_today",
				Handler: tvlist.GetAiringTodayTvHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/on_the_air",
				Handler: tvlist.GetOnTheAirTvHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/popular",
				Handler: tvlist.GetPopularTvHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/top_rated",
				Handler: tvlist.GetTopRatedTvHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v3"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/tv/:series_id/season/:season_number",
				Handler: tvseason.GetTvSeasonDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/:series_id/season/:season_number/credits",
				Handler: tvseason.GetTvSeasonCreditsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/:series_id/season/:season_number/episode/:episode_number",
				Handler: tvseason.GetTvEpisodeDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/:series_id/season/:season_number/episode/:episode_number/credits",
				Handler: tvseason.GetTvEpisodeCreditsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/:series_id/season/:season_number/episode/:episode_number/images",
				Handler: tvseason.GetTvEpisodeImagesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/:series_id/season/:season_number/images",
				Handler: tvseason.GetTvSeasonImagesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/:series_id/season/:season_number/videos",
				Handler: tvseason.GetTvSeasonVideosHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v3"),
	)
}
