version: "3.8"

services:
  app:
    image: ghcr.io/gatecross/ms_tmdb:latest
    container_name: ms_tmdb_app
    environment:
      TMDB_CONFIG_FILE: /app/etc/tmdb.yaml
    ports:
      - "8080:80"
    volumes:
      - ./tmdb.yaml:/app/etc/tmdb.yaml:ro
    restart: unless-stopped
